// This file is @generated by prost-build.
/// TxPvtReadWriteSetWithConfigInfo encapsulates the transaction's private
/// read-write set and additional information about the configurations such as
/// the latest collection config when the transaction is simulated
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxPvtReadWriteSetWithConfigInfo {
    #[prost(uint64, tag = "1")]
    pub endorsed_at: u64,
    #[prost(message, optional, tag = "2")]
    pub pvt_rwset: ::core::option::Option<super::rwset::TxPvtReadWriteSet>,
    #[prost(map = "string, message", tag = "3")]
    pub collection_configs: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::protos::CollectionConfigPackage,
    >,
}
